// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2lDiUw_H3iSOOhtgYEULScC1xUmn5Pk',
    appId: '1:308090552095:web:50a096804b028a1ae8ba2a',
    messagingSenderId: '308090552095',
    projectId: 'fluttalk',
    authDomain: 'fluttalk.firebaseapp.com',
    storageBucket: 'fluttalk.appspot.com',
    measurementId: 'G-WHFR34FJT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIl-n52XB3yG__EwKjRL-YPuj1yoWE9Qs',
    appId: '1:308090552095:android:a58abf5313230095e8ba2a',
    messagingSenderId: '308090552095',
    projectId: 'fluttalk',
    storageBucket: 'fluttalk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPomEC_H11x1mIEZ5UVvJEc_NhHCBYEu8',
    appId: '1:308090552095:ios:2cf734ed36739beee8ba2a',
    messagingSenderId: '308090552095',
    projectId: 'fluttalk',
    storageBucket: 'fluttalk.appspot.com',
    iosBundleId: 'org.flutterseoul.fluttalk',
  );
}